// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Architecture {
    using System;
    using UnityEngine;
    
    
    [UnityEngine.CreateAssetMenuAttribute()]
    public class FloatVariable : UnityEngine.ScriptableObject {
        
        private float DefaultValue;
        
        private float Value;
        
        public float CurrentValue {
            get {
                return this.Value;
            }
            set {
                this.Value = value;
            }
        }
        
        private void OnEnable() {
            this.Value = this.DefaultValue;
        }
    }
}
