// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Architecture {
    using System;
    using UnityEngine;
    
    
    [System.SerializableAttribute()]
    public class FloatReference {
        
        public float ConstantValue;
        
        public bool UseConstant;
        
        public FloatVariable Variable;
        
        public static implicit operator float(FloatReference reference)
        {
            return reference.Value;
        }

        public FloatReference() {
        }
        
        public FloatReference(float value) {
            this.ConstantValue = value;
            this.UseConstant = true;
        }
        
        public float Value {
            get {
                if (this.UseConstant) {
                    return this.ConstantValue;
                }
                else {
                    return this.Variable.CurrentValue;
                }
            }
            set {
                if (this.UseConstant) {
                    this.ConstantValue = value;
                }
                else {
                    this.Variable.CurrentValue = value;
                }
            }
        }
    }
}
